### ISSUE TITLE
roguereddwarf - ChainlinkOracle.sol + ChainlinkFeedOracle.sol: When a new phase is entered a price with "updatedAt" timestamp prior to the last price update might be used

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-perennial-judging#1]
roguereddwarf

high

# ChainlinkOracle.sol + ChainlinkFeedOracle.sol: When a new phase is entered a price with "updatedAt" timestamp prior to the last price update might be used

## Summary
The `ChainlinkOracle` contract downstream calls the Chainlink `FeedRegistry` to query prices.

It's possible that the `aggregator` in the `FeedRegistry` is changed and a new `phase` is entered.

When the new `aggregator` is then queried for the latest price data, the price data may have an `updatedAt` timestamp that is earlier than the latest `updatedAt` timestamp of the previous aggregator.

This means that positions of users are opened, closed, liquidated with a new price that is older than the last price.

The same scenario is possible in the `ChainlinkFeedOracle` as well which makes use of the Chainlink `AggregatorProxy`.

However this scenario is less likely in the `ChainlinkFeedOracle` because some execution paths there contain the check that the timestamp from the next phase must be bigger than the last timestamp from the old phase.

Therefore in the next section I will show how this issue can occur in the `ChainlinkOracle`. The suggestion I give in the end applies to both the `ChainlinkOracle` and `ChainlinkFeedOracle`.

## Vulnerability Detail
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-oracle/contracts/ChainlinkOracle.sol#L59-L79

Assume the last time the Oracle was synced it was in phase 1 with ETH/USD price of $1800 and `updatedAt=100`.

Now the `aggregator` is changed by Chainlink (next `phase` is entered) and the next time `sync` is called the new `aggregator` is queried

The price may have been last updated before `timestamp 100` such that the return might look something like:
`answer=$1790, updatedAt=90`.

## Impact
Positions can be incorrectly opened, closed, liquidated with the old price.
E.g. a user might be unfairly liquidated due to the price at $1790 when actually the price never dropped there after the timestamp 100.
This is a loss of funds.

## Code Snippet
`FeedRegistry` contract from Chainlink:
https://github.com/smartcontractkit/feed-registry/blob/master/contracts/FeedRegistry.sol

`ChainlinkOracle` contract:
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-oracle/contracts/ChainlinkOracle.sol#L59-L79

`ChainlinkFeedOracle` contract:
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-oracle/contracts/ChainlinkFeedOracle.sol#L92-L159

## Tool used
Manual Review

## Recommendation
It is necessary to check that for subsequent data from Chainlink `d` and `d+1` it holds true that `d.updatedAt < (d+1).updatedAt`. If this is not true the `sync` function must revert and wait for the new `aggregator` to get a new price update or fallback to the last price (the more recent one).

This means that the Oracles should have an additional storage variable that keeps track of the last synced version of the Oracle such that the above described check can be applied.

**Comment by roguereddwarf** [comment]
Escalate for 10 USDC

Quoting from the spreadsheet that the Lead Judge provided with reason as to why the issue is excluded:
> Without clear evidence that a new aggregator can have a round with a timestamp that is smaller than a previous round's timestamp, this seems invalid. Note that in this page: https://docs.chain.link/data-feeds/historical-data it is mentioned that getting rounds from Chainlink can be abstracted by using the proxy contract, which *only receives the round id*. So it seems that rounds are consecutive regardless of aggregator used.

The clear evidence is that there are no guarantees from Chainlink regarding timestamps for subsequent phases.
In other words there is no evidence that this scenario CANNOT occur.

By looking at the `AggregatorProxy` implementation from Chainlink, we can see that there are no checks regarding the timestamps when a new aggregator is set and a new phase is entered (https://github.com/smartcontractkit/chainlink/blob/270a179fb3c0233fe7c8b49229ea5cf9a44b116a/contracts/src/v0.6/AggregatorProxy.sol#L383-L389)

The sponsor explicitly stated in the contest README that they want to receive reports with edge cases regarding Chainlink:
![2023-06-30_09-55](https://github.com/sherlock-audit/2023-05-perennial-judging/assets/118631472/58c6495c-6345-44b2-b150-a2498a3bd09b)

So I agree that this is an unlikely scenario but I think this should be considered as a valid Medium issue because it can occur as part of an aggregator update in the Proxy contract, leading as I pointed out, to settlement at unintended prices.

**Comment by KenzoAgada** [comment]
Doesn't seem valid to me.

> The clear evidence is that there are no guarantees from Chainlink regarding timestamps for subsequent phases.
In other words there is no evidence that this scenario CANNOT occur.

Chainlink works in increasing rounds with increasing timestamps.
Users use the proxy contract that abstracts away the whole underlying implementation of aggregators and phases.
The fact that there can be phase switchovers doesn't imply that suddenly rounds will go backwards in time.
There is [this](https://ethereum.stackexchange.com/questions/150601/what-are-the-guarantees-around-chainlink-updatedat-timestamp) SO answer, which is not substantiated, but also points to this direction.
I find the saying "there is no evidence that this scenario CANNOT occur" too general, the burden of proof is on he who asserts something.
This might be an added sanity check but I do not believe this is a valid medium or high severity.

**Comment by jacksanford1** [comment]
@roguereddwarf Any response to @KenzoAgada?

**Comment by roguereddwarf** [comment]
I think it's ok that this isn't a valid issue.

**Comment by jacksanford1** [comment]
Result:
Invalid
Unique
Issue submitter/escalator agrees with Lead Judge's last comment.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [roguereddwarf](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/1/#issuecomment-1615081022): rejected
