### ISSUE TITLE
Emmanuel - Position fees will cause collateral balance of an account to go below `minCollateral`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-perennial-judging#123]
Emmanuel

medium

# Position fees will cause collateral balance of an account to go below `minCollateral`

## Summary
There is a minimum collateral that is set in the Controller contract. This disallows users from depositing collateral that would make collateral balance less than minimum Collateral, and prevents withdraws that would make the collateral balance less than minimum collateral.
This issue explains how an account can cause his collateral balance to go below the minCollateral and even open positions with it, hence defeating the purpose of minCollateral

## Vulnerability Detail
Opening a position debits a takerFee or makerFee, depending on the position opened, from the collateral balance, and then checks if the collateral will be enough after the next settlement.
The problem is that the functions do not check if the collateral balance, after deducting the fees, is more than minCollateral. This would allow the following:
- User deposits collateral that is just a little above minCollateral
- User opens and closes positions, so position fees makes the balance less than minCollateral
- User repeats above step till his balance reaches the point when liquidators pay a higher gas fee than the liquidation fee he would receive
- User opens a risky position, but liquidators will be dissuaded from liquidating it

One of the purposes of minCollateral is to allow for gas costs that would cover liquidation.
- User can calculate a collateral balance(liquidationBalance) that would be less than gas costs on ethereum to dissuade liquidators from liquidating his account even when his collateral balance is well below the required maintenance.
- User would then open and close a position that would make his collateral balance liquidationBalance after fees are deducted
- User would open positions using liquidationBalance as collateral, and be rest assured that liquidators won't want to liquidate his account.

NOTE: There is no strict mechanism to liquidate account when it falls below minCollateral
## Impact
A user can cause his collateral balance to be any value, even below minCollateral. With this power, he can make his collateral balance such that there would be no incentive to liquidate it.
Now, even when massive changes in Product's token price causes his collateral balance to be far less than the maintenance required, User's account may not be liquidated as there are no incentives for doing so.

## Code Snippet
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/product/Product.sol#L225
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/product/Product.sol#L266
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/product/Product.sol#L307
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/product/Product.sol#L349

## Tool used

Manual Review

## Recommendation
- Allow liquidation of an account whose collateral balance has fallen below minCollateral.(This would take care of instances when fundingFees causes the collateral balance to fall below minCollateral)
- Alternatively, Create a modifier in openMake and openTake founctions that ensures that after debiting the open+close position fees, the collateral balance does not fall below minCollateral

Duplicate of #103

**Comment by SergeKireev** [comment]
Escalate for 10 USDC

This report should be low/informational. For the liquidator to get less than `MIN_COLLATERAL*liquidationFee`, the total collateral left for the user should be less than `MIN_COLLATERAL*liquidationFee`.
With current market parameters:
MIN_COLLATERAL = 10 USD
liquidationFee = 0.05

This means that the malicious user would need to start with 10 USD and give up 95% of it to fees (not counting gas) making this `attack` highly unprofitable and should  not be eligible for medium severity as per sherlock rules:
https://docs.sherlock.xyz/audits/judging/judging

> The more expensive the attack is for an attacker, the less likely it will be included as a Medium (holding all other factors constant)

**Comment by KenzoAgada** [comment]
(Posting similar comment on #103 and #123. These have the same impact, but arise from different points in the code.)
I think that the escalation misses the problem that the issue points to.
The problem is not that liquidators will get less than `MIN_COLLATERAL*liquidationFee` after 95% of the collateral has been liquidated.
The problem is that after position fees are deducted from the position, the whole collateral of the account might be less than `MIN_COLLATERAL`. Already at that point, liquidators have no incentive to liquidate the account.

So the comment in the escalation that the user would have to lose 95% of his collateral is wrong.
Therefore I think that the escalation missed the problem and is invalid.

**Comment by KenzoAgada** [comment]
Please see my comments for issue #103. The issues share the same impact and I believe Sherlock's decision for #103 should go here as well.

**Comment by jacksanford1** [comment]
@KenzoAgada What is your decision after hearing @SergeKireev's argument?

**Comment by jacksanford1** [comment]
@SergeKireev @emedudu this issue will be tied to #103 from here. But it's a bit awkward since Emmanuel created both issues, so if they are both valid and duped together, then one issue will essentially not earn any credit.

**Comment by jacksanford1** [comment]
Result:
Low
Duplicate of #103 
This issue is similar to issue #103 (as Kenzo suggested) and much of the discussion in that issue is relevant here. Please see that discussion for full reasoning on why this issue is marked as Low.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [SergeKireev](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/123/#issuecomment-1613528937): accepted
