### ISSUE TITLE
levi - Incentive program refunds are not claimable

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-perennial-judging#139]
levi

medium

# Incentive program refunds are not claimable

## Summary

Incentive program rewards are not claimable

## Vulnerability Detail

When a program is complete, the refund amount is added to `settled[treasury]`.

```solidity
    function complete(
        Program storage self,
        IProduct product,
        ProgramInfo memory programInfo
    ) internal returns (uint256 versionComplete) {
        ...
        self.settled[treasury] = self.settled[treasury].add(refundAmount);
    }
```

The refund amount is never pushed to the treasury after this and there is no functionality to claim it.

## Impact

Refund amount can not be claimed.

## Code Snippet

https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/incentivizer/types/Program.sol#L57-L74

## Tool used

Manual Review

## Recommendation

Implement functionality to claim refunds

**Comment by leviack3rman** [comment]
Escalate for 10 USDC

This is a similar issue to issue #43 and #150

**Comment by arjun-io** [comment]
The incentive refunds can be claimed via the `claimFee` function: https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/incentivizer/Incentivizer.sol#L213

**Comment by arjun-io** [comment]
The tokens can be claimed via the `claim` function: https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/incentivizer/Incentivizer.sol#L138

The `settled[treasury]` call allocates the tokens to the treasury address to make them available for claiming

**Comment by KenzoAgada** [comment]
> Escalate for 10 USDC
> 
> This is a similar issue to issue #43 and #150

The issue is not similar to #43 and #150.
Sponsor is right, issue is invalid.

**Comment by jacksanford1** [comment]
@leviack3rman thoughts?

**Comment by leviack3rman** [comment]
I do agree the other duplicates issues I highlighted are different. The reason I raised this issue is that although there is a claim function as commented by the sponsor. This claim function seems to be for users participating in the market - https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/incentivizer/Incentivizer.sol#L138 . 

When the claim function is called, the global settlement and account settlement are done as per the modifier `settleForAccount(account, product)` - https://github.com/sherlock-audit/2023-05-perennial/blob/0f73469508a4cd3d90b382eac2112f012a5a9852/perennial-mono/packages/perennial/contracts/incentivizer/Incentivizer.sol#L181-L190 . Does this mean that the treasury address has to be a participant in a market?

I would believe that the treasury address is not a regular market participant and can be any address specified in the controller. I stand to be corrected if I am wrong.

**Comment by arjun-io** [comment]
See the test here: https://github.com/equilibria-xyz/perennial-mono/blob/dev2/packages/perennial/test/integration/core/incentivizer.test.ts#L199 which shows how the treasury's claimable balance is incremented with the refund amount.

**Comment by leviack3rman** [comment]
Yes, the unclaimed amount tracking part is OK. My question is how the tokens are eventually pushed to the treasury address. I can see it done for a regular market user here - https://github.com/equilibria-xyz/perennial-mono/blob/c8b51ff077c2029ab1733d53a6505c1be38facaf/packages/perennial/test/integration/core/incentivizer.test.ts#L186

Shouldn't there be a way for the treasury address to actually claim the amounts? The claim function that is available is for a regular user.

**Comment by arjun-io** [comment]
What do you mean by "just a regular user"? The Treasury just needs to call the Claim function on the incentivizer contract

**Comment by leviack3rman** [comment]
What I mean is that calling the Claim function invokes an account settlement process as I mentioned.

When the claim function is called, the global settlement and account settlement are done as per the modifier settleForAccount(account, product) - [https://github.com/sherlock-audit/2023-05-perennial/blob/0f73469508a4cd3d90b382eac2112f012a5a9852/perennial-mono/packages/perennial/contracts/incentivizer](https://github.com/sherlock-audit/2023-05-perennial/blob/0f73469508a4cd3d90b382eac2112f012a5a9852/perennial-mono/packages/perennial/contracts/incentivizer/Incentivizer.sol#L181-L190).

So if the treasury address calls this, the whole settlement process is initiated for the treasury address which is not a market participant.

**Comment by arjun-io** [comment]
That's correct, but if the account is not in the market that function will not revert. You can test this yourself by adding a `expect(await incentivizer.connect(treasuryA)['claim(address,uint256[])'](product.address, [PROGRAM_ID])).to.not.be
      .reverted` line to the above test

**Comment by leviack3rman** [comment]
Alright, Thanks. I'll try and investigate further if there are side effects of settling an account that isn't in the market.

**Comment by jacksanford1** [comment]
Will leave as Invalid unless @leviack3rman has an update.

**Comment by jacksanford1** [comment]
Result:
Invalid
Unique
Invalid based on Arjun's last comment and lack of update from escalator.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [leviack3rman](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/139/#issuecomment-1614079726): rejected
