### ISSUE TITLE
mstpr-brainbot - Vault rebalance can revert due to removing collateral before decreasing the position

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-perennial-judging#38]
mstpr-brainbot

medium

# Vault rebalance can revert due to removing collateral before decreasing the position

## Summary
When vault rebalances it first redeems the collateral without adjusting the position. In some cases such as withdrawals (claimedAmount) and sharp price movements redeeming the collateral first without adjusting the position can make the _settle function in vault revert constantly.
## Vulnerability Detail
For simplicity let's imagine a vault and two products with these properties:

1x leverage on vault
products maintenance is %51 (almost 2x leverage, unlikely but for the sake of example let's assume this)
price of the asset is 1$

assume at t=0
_latestEpoch = 2
longMarket.maker = 400, longMarket.taker = 200, shortMarket.maker = 400, shortMarket.taker = 200
vault.maker for long market = 100 and vault.maker for short market is 100
vault has 100, 100 collateral on both markets. 

assume at t=1, someone calls syncAccount(0)
_latestEpoch = 2, context.epoch = 3 and price is 2$ (2x from the previous version)
now first we need settle the product (markets) and for simplicity let's assume there are no position and funding fees, we will just accumulate the P&L

for the global accumulator:
oracleDelta = 1
totalTakerDelta = 200
socializedTakerDelta = 200
accumulator.maker = -1/2
accumulator.taker = 1

and when we add this to previous global accumulator it will be:
accumulator.taker = 200 (previous) + 1 (accumulated) = 201
accumulator.maker = 400 (previous) - 1/2 = 399.5

now let's do the account accumulator, remember we had 100, 100 position on both markets in the previous market and we had 100,100 collateral for each. 

for long market:
valueAccumulated.maker = 399.5 - 400 = -0.5
value = 100 * -0.5 = -50

for short market:
valueAccumulated.maker = 399.5 - 400 = -0.5
value = 100 * -0.5 = -50

for long market:
valueAccumulated.maker = 400.5 - 400 = 0.5
value = 100 * 0.5 = 50

so our total collat balances in long market:
100 (previous) - 50 = 50 

total collat balances in short market:
100(previous) + 50 = 150

and in total we have 150+50 = 200

now we need to rebalance back to 100-100 which means first we need to redeem our 50 from short market.

our short market position value is 100, and the price is now 2$
so the notionalMax = 100 * 2 = 200
and since maintenance is %51 our minimum collateral should be 200 * 0.51 = 102

when we try to withdraw the 50 the function will revert because of the modifier check in Collateral maintenanceInvariant since our position * maintenance() > collateral

In this case we had 150 we withdrew 50 and now we have 100 collateral but our position is 102 so it will revert. 

## Impact
Example above was a sharp price movement with a high maintenance(). However, we can also draw a scenario where price movement is not too much but funding + position fees are making our position value higher and there are some funds to claim (withdraw) from the market. In general, vault should be adjusting its position and then it should adjust the collateral balances. 
## Code Snippet
https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L375-L424

https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/contracts/balanced/BalancedVault.sol#L431-L465

https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/product/Product.sol#L84-L191

https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/product/types/accumulator/VersionedAccumulator.sol#L161-L175

https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/product/types/accumulator/AccountAccumulator.sol#L28-L38

https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/collateral/Collateral.sol#L72-L100

https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial/contracts/collateral/Collateral.sol#L263-L271
revert part
## Tool used

Manual Review

## Recommendation
Adjust position first before adjusting the collateral on markets.

Duplicate of #66

**Comment by SergeKireev** [comment]
Escalate for 10 USDC

This issue is invalid, see also my escalation on https://github.com/sherlock-audit/2023-05-perennial-judging/issues/47

Claiming is a two step process, where positions are first adjusted in the claim requesting phase, and collateral is removed during actual call to `claim`.

(See this integration test for proof: https://github.com/sherlock-audit/2023-05-perennial/blob/main/perennial-mono/packages/perennial-vaults/test/integration/BalancedVault/balancedVault.test.ts#L280-L356)

The report mentions price movements, and it is indeed possible that a vault gets liquidatable due to market conditions, which is normal behavior. The fact that `_rebalance` and `_settle` are called on every entry point of the vault seems to be mitigating this issue enough

**Comment by KenzoAgada** [comment]
I agree with escalator's comment. Issue is invalid.

**Comment by jacksanford1** [comment]
Ok, invalid. @mstpr

**Comment by jacksanford1** [comment]
Result:
Invalid
Duplicate of #66 
Based on escalator's comment and Lead Judge's agreement.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [SergeKireev](https://github.com/sherlock-audit/2023-05-perennial-judging/issues/38/#issuecomment-1614662583): accepted
